fregante/GhostText

README.md

> Since v2.0.0, Atomic Chrome for Emacs supports Ghost Text as browser extension.
From: <https://github.com/alpha22jp/atomic-chrome/blob/da84496/README.md>
In addition, I am written this pull request summary use the Emacs with your GhostText 😋 .

Readme: add the Atomic Chrome for Emacs

---

README.md

It's All Ghosts is a universal, yet limited script that brings back the basic It's All Text features for simple, non-plugin-aware editors.

Add link to It's All Ghosts

---

README.md

This changes add the link to a vim plugin which supports the GhostText.

Add link of vim plugin

---

README.md
package.json

Firefox now has a built-in UI for editing extension shortcuts, so we can
now re-enable the shortcut on Firefox, allowing users to update as they
wish.
Closes #147
The problematic shortcuts have been updated to Ctrl-Alt-E as suggested in #147
[when GhostText as a temporary extension as described in https://github.com/GhostText/GhostText/issues/147#issuecomment-496150163 neither the button nor the shortcut actually trigger the toggle properly, but that seems unrelated to this]

Alter suggested shortcut, and re-enable for Firefox.

---

package.json

Firefox autodeploy currently short circuits without attempting whenever the Chrome webstore autodeploy fails.
See discussion here: https://github.com/GhostText/GhostText/pull/159#issuecomment-531398418

Don't short circuit AMO autodeploy when CWS fails

---

package.json

Browser: Firefox
Editor: Any
The autodeploy for Firefox AMO fails to package the inputarea.js file, now that it's been re-enabled as part of #159 and #160
Building the package from scrach using webext works on my machine. I'm not yet sure why the autodeploy artifact is missing this specific file.
You can reproduce this issue by loading the latest release from the AMO. The issue is fatal and prevents the extension from working entirely.

Fix Mozilla Add-ons deployment 

---

browser/scripts/content.js

The field is automatically activated on GhostText click when:
- it's the only field on the page
- it's the only field left on the page (i.e. not yet active) unless there's an `iframe` (because there could be more fields in there)
- it's selected (closes #175)

Automatically pick the field more often

---

readme.md

- pandysong/ghost-text is still marked as "preliminary version" and the last update was in 2018
- falstro/ghost-text-vim doesn't work both ways and the last update was BC
- raghur/vim-ghost also works on Neovim, but for the sake of simplicity I'll keep it marked just as vim since there's a no-dependency neovim-only version

Reduce vim plugin choice in readme discarding outdated ones

---

source/ghost-text.js

There are some client-side JavaScript frameworks like React or Ember that without the `bubbles: true` option in the input event don't trigger its own `onChange` events when the input changes.
Two examples are of websites that don't work without this option are the email editor of [frontapp.com](https://frontapp.com/) and the post editor of all the [Discourse](https://www.discourse.org/) forums. I'm sure there will be many more 🙂

Bubble synthetic event so more websites can catch them

---

demo/index.html
source/ghost-text.js

Bitbucket Server pull requests use CodeMirror for code display and
textareas for line-comment widgets.
Check the field for an enclosing .CodeMirror-linewidget and skip the
CodeMirror hook-up when found. Without this change, editing a comment
instead pulls in the source code, and saving overwrites the markup on
the source. (Even with this change, editing the source itself wipes
out the widget.)
Extend the CodeMirror example in the demo so that clicking on a
linenumber toggles a textarea line widget into and out of existence.
The textarea as a widget reproduces the buggy behavior in the
version of the plugin before this commit.

Support fields nested in CodeMirror widgets

---

.terserrc
package-lock.json
package.json

Borrows some code from https://github.com/sindresorhus/notifier-for-github/pull/252 and https://github.com/fregante/browser-extension-template
Also hopefully cleans it up a little to help with the recent Chrome removal:

Meta: Improve the bundle

---

source/ghost-text.js

I was taking a look to see why [Notion](https://www.notion.so/) was not working properly and I noticed that for fields that are `contentEditable`, the events are not dispatched because the `contentEditable` wrapper doesn't have the `element.dispatchEvent` method bonded. Therefore, [this conditional](https://github.com/fregante/GhostText/blob/main/source/ghost-text.js#L163) is never run.
I wonder if that was on purpose or not. [Notion](https://www.notion.so/) seems to depend on the `input` event, so it woks fine after this modification.

Dispatch events on `contentEditable` elements

---

.gitignore
source/background.js
source/ghost-text.js
source/options-storage.js
source/options.css
source/options.html

Adds two options:
1. Show notification messages on (dis)connect (on by default)
2. Focus browser tab on disconnect (also on by default)
- closes https://github.com/fregante/GhostText/issues/243
- closes https://github.com/fregante/GhostText/issues/109

Add notification and focus options

---

source/ghost-text.js
source/unsafe-messenger.js

This pull request adds support for the Monaco Editor. This resolves issue #140, which requested the ability to use GhostText with the Monaco Editor.
The changes include a new condition in the `unsafe-messenger.js` file that checks for the existence of the `monaco` object, and a new function `monacoEditor(target)` that handles the events and value transfer for the Monaco Editor.
This has been tested and confirmed to work with the Monaco Editor, and should not affect the existing support for CodeMirror and Ace.
Here's a demo of the update:
https://user-images.githubusercontent.com/12979345/214165120-d559ea7e-8ebd-4083-9f0e-a3fbdcbc3bab.mp4

Add support for Monaco Editor

---

source/ghost-text.js
source/unsafe-messenger.js

I can't find why they were ever implemented. In the modern version I just recreated the API but never actually used it.

Drop unused blur events

---

PROTOCOL.md
source/ghost-text.js

"Selection change" events shouldn't need to send the text again

Allow optional `text` and `selections` in messages

---

source/background.js
source/manifest.json

- For https://github.com/fregante/GhostText/pull/245#issuecomment-1468735139
There's no default shortcut set because the other shortcut will also be dropped soon:
- #241 
The duplicate activation shortcut will likely dropped in the future. It's there because of an old browser bug (hopefully fixed now)

Add shortcut to disconnect fields

---

PROTOCOL.md

In https://github.com/fregante/GhostText-for-VSCode/commit/cb5ef60d469cb293cc061994c16c3580ad1e63d7 I verified that:
- The editor doesn't have to create a new WebSocket server for connection
- The WebSocket can share the same port as the HTTP server (default 4001)
The previous setup was carried over from the original proof of concept and never challenged.

Update Protocol to allow WebSocketPort/HTTP port reuse

---

package-lock.json
package.json
source/background.js
source/manifest.json

- Fixes #236 
- Follows https://github.com/fregante/GhostText/pull/284
- Works around https://bugzilla.mozilla.org/show_bug.cgi?id=1653408
- Related: https://github.com/pixiebrix/pixiebrix-extension/issues/5035
I had initially added this piece of code, but it makes GhostText more annoying, unnecessarily:
```diff
- async function handleAction({id}) {
+ async function handleAction({id, url}) {
+ 	await browser.permissions.request({
+ 		origins: [new URL(url).origin + '/*']
+ 	});
```

Improve support for frames in Firefox

---

PROTOCOL.md

While writing [GhostText-Any](https://github.com/newsch/GhostText-Any), I had some confusion about the contents of the `url`, `start`, and `end` properties.
I figured these clarifications would be helpful for anyone else interested in the protocol.

Add protocol notes

---

source/background.js

- Fixes #317 
I was able to reproduce the issue in Chrome + VSCode. This PR appears to fix it. Other editor plugins might need an update if they throw an error on unrecognized messages.

Avoid auto-disconnect when inactive

---

source/background.js
source/ghost-text.js

- Replaces #318 
- Fixes #317 
I think the previous fix worked for Chrome but not Firefox. This seems to work for quite a while in both browsers.

Avoid auto-disconnect in Firefox
