fregante/GhostText

- README.md
- messages/install.txt
Don’t force users to DE variant of the site.
> Fix links to Firefox Addons

- GhostText.py
- GhostText.sublime-settings
- GhostTextTools/Utils.py
- GhostTextTools/WindowHelper.py
> Extension-based syntax switching

- .travis.yml
- browser/package.json
- package.json
It will deploy the current version when a new tag is created.
Fixes #71
> Added autodeployment to Chrome Web Store on travis

- browser/scripts/InputArea/Detector.ts
- browser/scripts/InputArea/Selections.ts
- browser/scripts/InputArea/TextArea.ts
- browser/scripts/InputArea/dts/ace.d.ts
- browser/scripts/content.js
It may be silly, but I didn't like to see "text area" appear in the UI messages, so I changed them all.
> Fix "text area" text

- README.md
I implemented support for Acme text editor. It seems to be working well. I've tested on Chrome and Firefox.
> Readme: add link to Acme client

- README.md
Updated with link to repo for neovim plugin.
> Update README.md - added plugin for neovim

- README.md
- package.json
> Disable keyboard shortcut in Firefox

- PROTOCOL.md
Fixes issue #107
This describes the protocol in use so others may benefit when making their own GhostText compatible server.
> Add PROTOCOL.md

- README.md
New neovim plugin incorporated. 
Difference between different Vim plugins highlighted in **bold**
Extra whitespaces removed
> Improve vim plugin mentions in readme

- package-lock.json
- package.json
- readme.md
- source/background.js
- source/ghost-text.js
- source/humane-ghosttext.css
- source/options.html
> Add information and improve styling of options page

- readme.md
Follows https://github.com/sindresorhus/refined-github/pull/3983
I'll consider adding editor logos as well
Edit: Maybe on the mini site, if that materializes
> Update readme links style

- source/humane-ghosttext.css
> Slightly improve notifications style

- readme.md
> Meta: Move readme content to mini site

- source/background.js
> Allow activating GhostText by right clicking on fields

- package.json
- source/background.js
- source/options-storage.js
- source/options.js
- Fixes https://github.com/fregante/GhostText/issues/228
- Fixes https://github.com/fregante/GhostText/issues/227
> Restore GhostText again

- .github/workflows/release.yml
Testing https://github.com/fregante/web-ext-submit/pull/5
> Try new version of `web-ext-submit`

- source/background.js
Since the default shortcut will be removed due to https://github.com/fregante/GhostText/issues/241 and https://github.com/fregante/GhostText/issues/218, I'm preparing to preserve the shortcut for previous users.
> Preserve shortcut for upcoming removal of default

- package-lock.json
- package.json
- source/ghost-text.js
- source/unsafe-messenger.js
- Closes #238 
- https://discuss.codemirror.net/t/listen-to-text-changes-of-an-existing-state-view/5952
> Add support for CodeMirror 6

- safari/prepare-release.sh
- source/background.js
> Fix status badge on Safari

- source/background.js
> Restore keyboard shortcuts in Firefox

- source/background.js
- source/options.html
> Handle "Load failed" message on Safari

- .github/workflows/release.yml
- package-lock.json
- package.json
- source/background.js
- source/ghost-text.js
- source/manifest.json
- Blocked by https://github.com/parcel-bundler/parcel/issues/9458
I'm thinking I will ship MV3 to Chrome an block it on Firefox, hoping that there's no urgent Firefox bug between now and the next release of Parcel
> Use Manifest v3

- source/advanced-editors-messenger.js
- source/background.js
- source/ghost-text.js
- source/manifest.json
- Follows #314 
- Should fix https://github.com/fregante/GhostText/issues/237
- Might fix https://github.com/fregante/GhostText/issues/308
- Might fix https://github.com/fregante/GhostText/issues/283
Firefox 128 will be out on July 9th with support for the MAIN world:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1736575
> Improve compatibility with CSP pages

- .github/workflows/release.yml
- package-lock.json
- package.json
- source/manifest.json
Follows:
- https://github.com/fregante/GhostText/pull/314
- https://github.com/fregante/browser-extension-template/pull/97
- https://github.com/fregante/browser-extension-template/issues/78#issuecomment-2211684731
- https://github.com/parcel-bundler/parcel/discussions/9790#discussioncomment-9948725
> Meta: Drop Parcel MV3 workaround

- readme.md
Per https://github.com/fregante/GhostText/issues/343#issuecomment-2932593142
Thanks!
> Add Helix client to the README
